services:
  pg:
    image: pgvector/pgvector:pg16  # ⬅ has the vector extension preinstalled
    container_name: overmnd_pg
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
