[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]
src_paths = ["backend"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","I","B","UP","W","BLE"]
ignore = ["E402","B008"]

# Use a table-of-arrays (NOT inline) for per-file ignores.
[tool.ruff.lint.per-file-ignores]
"alembic/versions/*.py" = ["E501","I001","E402"]
"alembic/*.py" = ["E402"]
