name: Deploy admin (overmnd-admin)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend   # <-- change if your admin code lives elsewhere
    steps:
      - uses: actions/checkout@v4

      - name: Verify secret exists
        if: ${{ !secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_ADMIN }}
        run: |
          echo "Missing AZUREAPPSERVICE_PUBLISH_PROFILE_ADMIN" >&2
          exit 1

      # If you build client-side assets in CI, do it here (optional)
      # - run: npm ci && npm run build

      - name: Deploy to Azure Web App (deploy that folder)
        uses: azure/webapps-deploy@v3
        with:
          app-name: overmnd-admin
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_ADMIN }}
          package: frontend
