name: backend → Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/backend_overmnd-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy root requirements into backend
        run: cp requirements.txt backend/requirements.txt

      - name: Build with Oryx (Python 3.12) on runner
        uses: azure/appservice-build@v3
        with:
          platform: python
          platform-version: '3.12'
          source-directory: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: overmnd-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend
