name: deploy-backend

on:
  push:
    branches: [ backend ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_overmnd-backend.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login with OIDC (Deployment Center created these three repo secrets)
      - name: Az login
        uses: azure/login@v2
        with:
          client-id:        ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Make sure the app is configured to run an Oryx build on deploy
      - name: Ensure App Settings for Oryx build
        uses: azure/appservice-settings@v1
        with:
          app-name: overmnd-backend
          app-settings-json: |
            [
              {"name":"SCM_DO_BUILD_DURING_DEPLOYMENT","value":"true","slotSetting":false},
              {"name":"ENABLE_ORYX_BUILD","value":"true","slotSetting":false}
            ]

      # Deploy only the backend/ folder and let the server run Oryx (pip install)
      - name: Deploy to Azure Web App (Oryx)
        uses: azure/webapps-deploy@v2
        with:
          app-name: overmnd-backend
          package: ./backend
          enable-oryx-build: true
