name: backend_overmnd-backend
on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "requirements.txt"
      - ".github/workflows/backend_overmnd-backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package wwwroot
        run: zip -r sitepackage.zip backend requirements.txt

      - name: Deploy to Azure Web App (Zip Deploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: overmnd-backend
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: sitepackage.zip
