name: deploy-backend (overmnd-backend)

on:
  push:
    branches: [ backend ]
    paths:
      - "backend/**"
      - ".github/workflows/backend_overmnd-backend.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: overmnd-backend
      AZURE_RESOURCE_GROUP: AUS-Dev
      APP_ARTIFACT: build_output.zip
      APP_PATH: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Build the backend with Oryx (this produces a zip with deps baked in)
      - name: Oryx build (Python)
        uses: azure/appservice-build@v3
        with:
          repo-path: ${{ env.APP_PATH }}
          platform: python
          platform-version: "3.12"
          output-path: ${{ env.APP_ARTIFACT }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.APP_ARTIFACT }}

      - name: Show deployment URL
        run: echo "https://overmnd-backend-afd9a4f8eugredh6.australiacentral-01.azurewebsites.net/"
