name: Deploy backend (overmnd-backend)

on:
  push:
    branches: [main, backend]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanity — show root contents
        run: ls -la

      - name: Verify secret exists
        if: ${{ !secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_BACKEND }}
        run: |
          echo "Missing AZUREAPPSERVICE_PUBLISH_PROFILE_BACKEND" >&2
          exit 1

      - name: Deploy to Azure Web App (Zip Deploy from repo root)
        uses: azure/webapps-deploy@v3
        with:
          app-name: overmnd-backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_BACKEND }}
          package: .
