name: deploy-frontend

on:
  push:
    branches: [ frontend ]
    paths:
      - 'site/**'
      - '.github/workflows/frontend_overmnd-frontend.yml'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  # Embed real URLs at build time
  NEXT_PUBLIC_BACKEND_URL: "https://overmnd-backend-afd9a4f8eugredh6.australiacentral-01.azurewebsites.net"
  NEXT_PUBLIC_ADMIN_PORTAL_URL: "https://overmnd-admin-f2e9andnd3ggeta6.australiacentral-01.azurewebsites.net"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: site/package-lock.json

      - name: Install deps
        working-directory: site
        run: npm ci

      - name: Build
        working-directory: site
        run: npm run build

      - name: Static export
        working-directory: site
        run: npx next export -o out

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "overmnd-frontend"
          slot-name: "production"
          package: "site/out"

      - name: Logout
        run: az logout
